// ─── Static reference data ────────────────────────────────────────────────────
// This file contains ONLY static reference data used for UI dropdowns, labels,
// and ticker search. No simulated prices, charts, or performance data.

// ─── Instrument list ──────────────────────────────────────────────────────────
export const INSTRUMENTS = [
  // Broad market ETFs          expense_ratio = annual fee %;  div_yield = trailing 12mo yield %
  { ticker: 'SPY',  name: 'SPDR S&P 500 ETF Trust',             type: 'ETF',   exchange: 'NYSE',   last_price: 618.50,  expense_ratio: 0.0945, div_yield: 1.3  },
  { ticker: 'QQQ',  name: 'Invesco QQQ Trust (NASDAQ-100)',      type: 'ETF',   exchange: 'NASDAQ', last_price: 542.70,  expense_ratio: 0.20,   div_yield: 0.6  },
  { ticker: 'IWM',  name: 'iShares Russell 2000 ETF',            type: 'ETF',   exchange: 'NYSE',   last_price: 234.80,  expense_ratio: 0.19,   div_yield: 1.2  },
  { ticker: 'DIA',  name: 'SPDR Dow Jones Industrial Average ETF', type: 'ETF', exchange: 'NYSE',   last_price: 454.60,  expense_ratio: 0.16,   div_yield: 1.7  },
  { ticker: 'EFA',  name: 'iShares MSCI EAFE ETF',               type: 'ETF',   exchange: 'NYSE',   last_price: 78.44,   expense_ratio: 0.32,   div_yield: 3.0  },
  { ticker: 'ACWI', name: 'iShares MSCI ACWI ETF',               type: 'ETF',   exchange: 'NASDAQ', last_price: 110.62,  expense_ratio: 0.32,   div_yield: 1.8  },
  { ticker: 'EEM',  name: 'iShares MSCI Emerging Markets ETF',   type: 'ETF',   exchange: 'NYSE',   last_price: 44.18,   expense_ratio: 0.68,   div_yield: 2.5  },
  // Bond ETFs
  { ticker: 'AGG',  name: 'iShares Core U.S. Aggregate Bond',    type: 'ETF',   exchange: 'NYSE',   last_price: 97.20,   expense_ratio: 0.03,   div_yield: 4.2  },
  { ticker: 'BND',  name: 'Vanguard Total Bond Market ETF',      type: 'ETF',   exchange: 'NASDAQ', last_price: 73.88,   expense_ratio: 0.03,   div_yield: 4.1  },
  { ticker: 'TLT',  name: 'iShares 20+ Year Treasury Bond ETF',  type: 'ETF',   exchange: 'NASDAQ', last_price: 91.27,   expense_ratio: 0.15,   div_yield: 4.5  },
  { ticker: 'HYG',  name: 'iShares iBoxx High Yield Corp Bond',  type: 'ETF',   exchange: 'NYSE',   last_price: 78.54,   expense_ratio: 0.49,   div_yield: 6.5  },
  { ticker: 'LQD',  name: 'iShares iBoxx Investment Grade Corp', type: 'ETF',   exchange: 'NYSE',   last_price: 107.43,  expense_ratio: 0.14,   div_yield: 5.0  },
  { ticker: 'TIPS', name: 'iShares TIPS Bond ETF',               type: 'ETF',   exchange: 'NYSE',   last_price: 107.82,  expense_ratio: 0.19,   div_yield: 3.5  },
  // Other ETFs
  { ticker: 'VOO',  name: 'Vanguard S&P 500 ETF',                type: 'ETF',   exchange: 'NYSE',   last_price: 568.40,  expense_ratio: 0.03,   div_yield: 1.3  },
  { ticker: 'VTI',  name: 'Vanguard Total Stock Market ETF',     type: 'ETF',   exchange: 'NYSE',   last_price: 292.50,  expense_ratio: 0.03,   div_yield: 1.4  },
  { ticker: 'VGT',  name: 'Vanguard Information Technology ETF', type: 'ETF',   exchange: 'NYSE',   last_price: 625.80,  expense_ratio: 0.10,   div_yield: 0.6  },
  { ticker: 'VNQ',  name: 'Vanguard Real Estate ETF',            type: 'ETF',   exchange: 'NYSE',   last_price: 84.51,   expense_ratio: 0.12,   div_yield: 4.0  },
  { ticker: 'VWO',  name: 'Vanguard FTSE Emerging Markets ETF',  type: 'ETF',   exchange: 'NYSE',   last_price: 43.12,   expense_ratio: 0.08,   div_yield: 3.5  },
  { ticker: 'GLD',  name: 'SPDR Gold Shares',                    type: 'ETF',   exchange: 'NYSE',   last_price: 243.89,  expense_ratio: 0.40,   div_yield: 0    },
  { ticker: 'SLV',  name: 'iShares Silver Trust',                type: 'ETF',   exchange: 'NYSE',   last_price: 27.43,   expense_ratio: 0.50,   div_yield: 0    },
  { ticker: 'XLK',  name: 'Technology Select Sector SPDR',       type: 'ETF',   exchange: 'NYSE',   last_price: 228.43,  expense_ratio: 0.13,   div_yield: 0.7  },
  { ticker: 'XLF',  name: 'Financial Select Sector SPDR',        type: 'ETF',   exchange: 'NYSE',   last_price: 48.82,   expense_ratio: 0.13,   div_yield: 1.8  },
  { ticker: 'XLE',  name: 'Energy Select Sector SPDR',           type: 'ETF',   exchange: 'NYSE',   last_price: 92.17,   expense_ratio: 0.13,   div_yield: 3.2  },
  { ticker: 'XLV',  name: 'Health Care Select Sector SPDR',      type: 'ETF',   exchange: 'NYSE',   last_price: 138.95,  expense_ratio: 0.13,   div_yield: 1.5  },
  { ticker: 'XLI',  name: 'Industrial Select Sector SPDR',       type: 'ETF',   exchange: 'NYSE',   last_price: 133.72,  expense_ratio: 0.13,   div_yield: 1.3  },
  { ticker: 'XLY',  name: 'Consumer Discretionary Select Sector',type: 'ETF',   exchange: 'NYSE',   last_price: 212.38,  expense_ratio: 0.13,   div_yield: 0.8  },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR',      type: 'ETF',   exchange: 'NYSE',   last_price: 42.16,   expense_ratio: 0.13,   div_yield: 3.5  },
  { ticker: 'ARKK', name: 'ARK Innovation ETF',                  type: 'ETF',   exchange: 'NYSE',   last_price: 52.34,   expense_ratio: 0.75,   div_yield: 0    },
  { ticker: 'TQQQ', name: 'ProShares UltraPro QQQ',              type: 'ETF',   exchange: 'NASDAQ', last_price: 68.14,   expense_ratio: 0.88,   div_yield: 0.2  },
  { ticker: 'SQQQ', name: 'ProShares UltraPro Short QQQ',        type: 'ETF',   exchange: 'NASDAQ', last_price: 9.43,    expense_ratio: 0.95,   div_yield: 0    },
  { ticker: 'SOXX', name: 'iShares Semiconductor ETF',           type: 'ETF',   exchange: 'NASDAQ', last_price: 248.71,  expense_ratio: 0.35,   div_yield: 0.7  },
  // Additional popular ETFs
  { ticker: 'VXUS', name: 'Vanguard Total International Stock', type: 'ETF',   exchange: 'NASDAQ', last_price: 60.12,   expense_ratio: 0.07,   div_yield: 3.1  },
  { ticker: 'QQQM', name: 'Invesco NASDAQ 100 ETF',             type: 'ETF',   exchange: 'NASDAQ', last_price: 209.55,  expense_ratio: 0.15,   div_yield: 0.6  },
  { ticker: 'AVUV', name: 'Avantis US Small Cap Value ETF',     type: 'ETF',   exchange: 'NYSE',   last_price: 99.87,   expense_ratio: 0.25,   div_yield: 1.8  },
  { ticker: 'SCHD', name: 'Schwab US Dividend Equity ETF',      type: 'ETF',   exchange: 'NYSE',   last_price: 28.42,   expense_ratio: 0.06,   div_yield: 3.4  },
  { ticker: 'XLU',  name: 'Utilities Select Sector SPDR',       type: 'ETF',   exchange: 'NYSE',   last_price: 75.83,   expense_ratio: 0.13,   div_yield: 2.8  },
  { ticker: 'GLTR', name: 'abrdn Physical Precious Metals ETF', type: 'ETF',   exchange: 'NYSE',   last_price: 108.92,  expense_ratio: 0.60,   div_yield: 0    },
  { ticker: 'BITW', name: 'Bitwise 10 Crypto Index Fund',       type: 'ETF',   exchange: 'OTC',    last_price: 38.56,   expense_ratio: 2.50,   div_yield: 0    },
  { ticker: 'IBIT', name: 'iShares Bitcoin Trust ETF',           type: 'ETF',   exchange: 'NASDAQ', last_price: 58.90,   expense_ratio: 0.25,   div_yield: 0    },
  { ticker: 'JEPI', name: 'JPMorgan Equity Premium Income ETF', type: 'ETF',   exchange: 'NYSE',   last_price: 57.12,   expense_ratio: 0.35,   div_yield: 7.2  },
  { ticker: 'JEPQ', name: 'JPMorgan Nasdaq Equity Premium Income', type: 'ETF', exchange: 'NASDAQ', last_price: 53.88,  expense_ratio: 0.35,   div_yield: 9.5  },
  { ticker: 'VIG',  name: 'Vanguard Dividend Appreciation ETF', type: 'ETF',   exchange: 'NYSE',   last_price: 188.76,  expense_ratio: 0.06,   div_yield: 1.8  },
  { ticker: 'SPLG', name: 'SPDR Portfolio S&P 500 ETF',         type: 'ETF',   exchange: 'NYSE',   last_price: 67.28,   expense_ratio: 0.02,   div_yield: 1.3  },
  // Large-cap Tech                                                               expense_ratio: 0 for all stocks
  { ticker: 'AAPL', name: 'Apple Inc.',                          type: 'Stock', exchange: 'NASDAQ', last_price: 242.30,  expense_ratio: 0,      div_yield: 0.5  },
  { ticker: 'MSFT', name: 'Microsoft Corporation',               type: 'Stock', exchange: 'NASDAQ', last_price: 438.90,  expense_ratio: 0,      div_yield: 0.7  },
  { ticker: 'GOOGL',name: 'Alphabet Inc. Class A',               type: 'Stock', exchange: 'NASDAQ', last_price: 205.40,  expense_ratio: 0,      div_yield: 0.5  },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C',               type: 'Stock', exchange: 'NASDAQ', last_price: 207.15,  expense_ratio: 0,      div_yield: 0.5  },
  { ticker: 'AMZN', name: 'Amazon.com Inc.',                     type: 'Stock', exchange: 'NASDAQ', last_price: 238.60,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'NVDA', name: 'NVIDIA Corporation',                  type: 'Stock', exchange: 'NASDAQ', last_price: 142.50,  expense_ratio: 0,      div_yield: 0.03 },
  { ticker: 'META', name: 'Meta Platforms Inc.',                 type: 'Stock', exchange: 'NASDAQ', last_price: 695.20,  expense_ratio: 0,      div_yield: 0.3  },
  { ticker: 'TSLA', name: 'Tesla Inc.',                          type: 'Stock', exchange: 'NASDAQ', last_price: 362.80,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'ADBE', name: 'Adobe Inc.',                          type: 'Stock', exchange: 'NASDAQ', last_price: 524.83,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'CRM',  name: 'Salesforce Inc.',                     type: 'Stock', exchange: 'NYSE',   last_price: 303.14,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'NFLX', name: 'Netflix Inc.',                        type: 'Stock', exchange: 'NASDAQ', last_price: 1028.40, expense_ratio: 0,      div_yield: 0    },
  { ticker: 'ORCL', name: 'Oracle Corporation',                  type: 'Stock', exchange: 'NYSE',   last_price: 174.22,  expense_ratio: 0,      div_yield: 1.1  },
  { ticker: 'NOW',  name: 'ServiceNow Inc.',                     type: 'Stock', exchange: 'NYSE',   last_price: 940.18,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'SHOP', name: 'Shopify Inc.',                        type: 'Stock', exchange: 'NYSE',   last_price: 117.48,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'UBER', name: 'Uber Technologies Inc.',              type: 'Stock', exchange: 'NYSE',   last_price: 74.92,   expense_ratio: 0,      div_yield: 0    },
  { ticker: 'SPOT', name: 'Spotify Technology S.A.',             type: 'Stock', exchange: 'NYSE',   last_price: 477.51,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'APP',  name: 'Applovin Corporation',                type: 'Stock', exchange: 'NASDAQ', last_price: 342.15,  expense_ratio: 0,      div_yield: 0    },
  // Semiconductors
  { ticker: 'AMD',  name: 'Advanced Micro Devices Inc.',         type: 'Stock', exchange: 'NASDAQ', last_price: 178.83,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'INTC', name: 'Intel Corporation',                   type: 'Stock', exchange: 'NASDAQ', last_price: 24.38,   expense_ratio: 0,      div_yield: 2.0  },
  { ticker: 'QCOM', name: 'Qualcomm Inc.',                       type: 'Stock', exchange: 'NASDAQ', last_price: 186.40,  expense_ratio: 0,      div_yield: 2.1  },
  { ticker: 'AVGO', name: 'Broadcom Inc.',                       type: 'Stock', exchange: 'NASDAQ', last_price: 228.40,  expense_ratio: 0,      div_yield: 1.1  },
  { ticker: 'TXN',  name: 'Texas Instruments Inc.',              type: 'Stock', exchange: 'NASDAQ', last_price: 195.87,  expense_ratio: 0,      div_yield: 2.7  },
  { ticker: 'MU',   name: 'Micron Technology Inc.',              type: 'Stock', exchange: 'NASDAQ', last_price: 108.42,  expense_ratio: 0,      div_yield: 0.4  },
  { ticker: 'AMAT', name: 'Applied Materials Inc.',              type: 'Stock', exchange: 'NASDAQ', last_price: 192.76,  expense_ratio: 0,      div_yield: 0.8  },
  { ticker: 'LRCX', name: 'Lam Research Corporation',           type: 'Stock', exchange: 'NASDAQ', last_price: 817.29,  expense_ratio: 0,      div_yield: 1.1  },
  { ticker: 'KLAC', name: 'KLA Corporation',                    type: 'Stock', exchange: 'NASDAQ', last_price: 812.47,  expense_ratio: 0,      div_yield: 0.6  },
  { ticker: 'ARM',  name: 'Arm Holdings plc',                   type: 'Stock', exchange: 'NASDAQ', last_price: 148.32,  expense_ratio: 0,      div_yield: 0    },
  // Financials
  { ticker: 'JPM',  name: 'JPMorgan Chase & Co.',                type: 'Stock', exchange: 'NYSE',   last_price: 244.78,  expense_ratio: 0,      div_yield: 2.0  },
  { ticker: 'BAC',  name: 'Bank of America Corporation',         type: 'Stock', exchange: 'NYSE',   last_price: 44.36,   expense_ratio: 0,      div_yield: 2.4  },
  { ticker: 'GS',   name: 'Goldman Sachs Group Inc.',            type: 'Stock', exchange: 'NYSE',   last_price: 584.20,  expense_ratio: 0,      div_yield: 2.0  },
  { ticker: 'MS',   name: 'Morgan Stanley',                      type: 'Stock', exchange: 'NYSE',   last_price: 128.55,  expense_ratio: 0,      div_yield: 3.3  },
  { ticker: 'WFC',  name: 'Wells Fargo & Company',               type: 'Stock', exchange: 'NYSE',   last_price: 76.34,   expense_ratio: 0,      div_yield: 2.6  },
  { ticker: 'V',    name: 'Visa Inc.',                           type: 'Stock', exchange: 'NYSE',   last_price: 314.92,  expense_ratio: 0,      div_yield: 0.7  },
  { ticker: 'MA',   name: 'Mastercard Incorporated',             type: 'Stock', exchange: 'NYSE',   last_price: 522.18,  expense_ratio: 0,      div_yield: 0.5  },
  { ticker: 'AXP',  name: 'American Express Company',            type: 'Stock', exchange: 'NYSE',   last_price: 290.44,  expense_ratio: 0,      div_yield: 1.0  },
  { ticker: 'BLK',  name: 'BlackRock Inc.',                      type: 'Stock', exchange: 'NYSE',   last_price: 1012.34, expense_ratio: 0,      div_yield: 2.4  },
  { ticker: 'SCHW', name: 'Charles Schwab Corporation',          type: 'Stock', exchange: 'NYSE',   last_price: 78.14,   expense_ratio: 0,      div_yield: 1.5  },
  { ticker: 'COF',  name: 'Capital One Financial Corporation',   type: 'Stock', exchange: 'NYSE',   last_price: 192.80,  expense_ratio: 0,      div_yield: 1.7  },
  // Healthcare & Pharma
  { ticker: 'AMGN', name: 'Amgen Inc.',                          type: 'Stock', exchange: 'NASDAQ', last_price: 268.79,  expense_ratio: 0,      div_yield: 3.0  },
  { ticker: 'JNJ',  name: 'Johnson & Johnson',                   type: 'Stock', exchange: 'NYSE',   last_price: 162.40,  expense_ratio: 0,      div_yield: 3.1  },
  { ticker: 'UNH',  name: 'UnitedHealth Group Incorporated',     type: 'Stock', exchange: 'NYSE',   last_price: 524.15,  expense_ratio: 0,      div_yield: 1.4  },
  { ticker: 'PFE',  name: 'Pfizer Inc.',                         type: 'Stock', exchange: 'NYSE',   last_price: 28.57,   expense_ratio: 0,      div_yield: 6.5  },
  { ticker: 'ABBV', name: 'AbbVie Inc.',                         type: 'Stock', exchange: 'NYSE',   last_price: 175.43,  expense_ratio: 0,      div_yield: 3.3  },
  { ticker: 'LLY',  name: 'Eli Lilly and Company',              type: 'Stock', exchange: 'NYSE',   last_price: 798.45,  expense_ratio: 0,      div_yield: 0.6  },
  { ticker: 'MRK',  name: 'Merck & Co. Inc.',                   type: 'Stock', exchange: 'NYSE',   last_price: 103.22,  expense_ratio: 0,      div_yield: 2.5  },
  { ticker: 'GILD', name: 'Gilead Sciences Inc.',               type: 'Stock', exchange: 'NASDAQ', last_price: 90.14,   expense_ratio: 0,      div_yield: 3.5  },
  { ticker: 'ISRG', name: 'Intuitive Surgical Inc.',            type: 'Stock', exchange: 'NASDAQ', last_price: 524.82,  expense_ratio: 0,      div_yield: 0    },
  // Consumer
  { ticker: 'PG',   name: 'Procter & Gamble Co.',                type: 'Stock', exchange: 'NYSE',   last_price: 165.82,  expense_ratio: 0,      div_yield: 2.3  },
  { ticker: 'HD',   name: 'Home Depot Inc.',                     type: 'Stock', exchange: 'NYSE',   last_price: 407.26,  expense_ratio: 0,      div_yield: 2.3  },
  { ticker: 'DIS',  name: 'Walt Disney Company',                 type: 'Stock', exchange: 'NYSE',   last_price: 114.27,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'COST', name: 'Costco Wholesale Corporation',        type: 'Stock', exchange: 'NASDAQ', last_price: 958.43,  expense_ratio: 0,      div_yield: 0.5  },
  { ticker: 'WMT',  name: 'Walmart Inc.',                        type: 'Stock', exchange: 'NYSE',   last_price: 93.52,   expense_ratio: 0,      div_yield: 1.0  },
  { ticker: 'TGT',  name: 'Target Corporation',                  type: 'Stock', exchange: 'NYSE',   last_price: 139.24,  expense_ratio: 0,      div_yield: 3.0  },
  { ticker: 'MCD',  name: "McDonald's Corporation",              type: 'Stock', exchange: 'NYSE',   last_price: 298.76,  expense_ratio: 0,      div_yield: 2.2  },
  { ticker: 'SBUX', name: 'Starbucks Corporation',               type: 'Stock', exchange: 'NASDAQ', last_price: 92.44,   expense_ratio: 0,      div_yield: 3.2  },
  { ticker: 'NKE',  name: 'Nike Inc.',                           type: 'Stock', exchange: 'NYSE',   last_price: 81.23,   expense_ratio: 0,      div_yield: 2.0  },
  { ticker: 'KO',   name: 'Coca-Cola Company',                   type: 'Stock', exchange: 'NYSE',   last_price: 63.18,   expense_ratio: 0,      div_yield: 3.0  },
  { ticker: 'PEP',  name: 'PepsiCo Inc.',                        type: 'Stock', exchange: 'NASDAQ', last_price: 152.42,  expense_ratio: 0,      div_yield: 3.3  },
  // Energy
  { ticker: 'XOM',  name: 'Exxon Mobil Corporation',             type: 'Stock', exchange: 'NYSE',   last_price: 112.84,  expense_ratio: 0,      div_yield: 3.2  },
  { ticker: 'CVX',  name: 'Chevron Corporation',                 type: 'Stock', exchange: 'NYSE',   last_price: 163.52,  expense_ratio: 0,      div_yield: 4.3  },
  { ticker: 'COP',  name: 'ConocoPhillips',                      type: 'Stock', exchange: 'NYSE',   last_price: 116.39,  expense_ratio: 0,      div_yield: 3.0  },
  { ticker: 'SLB',  name: 'Schlumberger N.V.',                   type: 'Stock', exchange: 'NYSE',   last_price: 44.82,   expense_ratio: 0,      div_yield: 2.7  },
  // Industrials / Other
  { ticker: 'CAT',  name: 'Caterpillar Inc.',                    type: 'Stock', exchange: 'NYSE',   last_price: 390.47,  expense_ratio: 0,      div_yield: 1.5  },
  { ticker: 'BA',   name: 'Boeing Company',                      type: 'Stock', exchange: 'NYSE',   last_price: 170.38,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'GE',   name: 'GE Aerospace',                        type: 'Stock', exchange: 'NYSE',   last_price: 192.85,  expense_ratio: 0,      div_yield: 0.7  },
  { ticker: 'HON',  name: 'Honeywell International Inc.',        type: 'Stock', exchange: 'NASDAQ', last_price: 214.63,  expense_ratio: 0,      div_yield: 2.2  },
  { ticker: 'RTX',  name: 'RTX Corporation',                     type: 'Stock', exchange: 'NYSE',   last_price: 131.44,  expense_ratio: 0,      div_yield: 2.0  },
  { ticker: 'LMT',  name: 'Lockheed Martin Corporation',         type: 'Stock', exchange: 'NYSE',   last_price: 500.78,  expense_ratio: 0,      div_yield: 2.7  },
  { ticker: 'UPS',  name: 'United Parcel Service Inc.',          type: 'Stock', exchange: 'NYSE',   last_price: 129.54,  expense_ratio: 0,      div_yield: 4.5  },
  { ticker: 'FDX',  name: 'FedEx Corporation',                   type: 'Stock', exchange: 'NYSE',   last_price: 282.41,  expense_ratio: 0,      div_yield: 2.2  },
  { ticker: 'BRK.B',name: 'Berkshire Hathaway Inc. Class B',    type: 'Stock', exchange: 'NYSE',   last_price: 450.91,  expense_ratio: 0,      div_yield: 0    },
  // Fintech / Growth
  { ticker: 'PYPL', name: 'PayPal Holdings Inc.',                type: 'Stock', exchange: 'NASDAQ', last_price: 86.93,   expense_ratio: 0,      div_yield: 0    },
  { ticker: 'SNOW', name: 'Snowflake Inc.',                      type: 'Stock', exchange: 'NYSE',   last_price: 146.38,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.',          type: 'Stock', exchange: 'NYSE',   last_price: 118.50,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'COIN', name: 'Coinbase Global Inc.',                type: 'Stock', exchange: 'NASDAQ', last_price: 298.40,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'RBLX', name: 'Roblox Corporation',                  type: 'Stock', exchange: 'NYSE',   last_price: 42.31,   expense_ratio: 0,      div_yield: 0    },
  { ticker: 'DDOG', name: 'Datadog Inc.',                        type: 'Stock', exchange: 'NASDAQ', last_price: 121.48,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings Inc.',           type: 'Stock', exchange: 'NASDAQ', last_price: 368.92,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'ZS',   name: 'Zscaler Inc.',                        type: 'Stock', exchange: 'NASDAQ', last_price: 212.54,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'NET',  name: 'Cloudflare Inc.',                     type: 'Stock', exchange: 'NYSE',   last_price: 117.82,  expense_ratio: 0,      div_yield: 0    },
  { ticker: 'S',    name: 'SentinelOne Inc.',                    type: 'Stock', exchange: 'NYSE',   last_price: 21.45,   expense_ratio: 0,      div_yield: 0    },
  // Telecom / Media
  { ticker: 'T',    name: 'AT&T Inc.',                           type: 'Stock', exchange: 'NYSE',   last_price: 19.87,   expense_ratio: 0,      div_yield: 5.5  },
  { ticker: 'VZ',   name: 'Verizon Communications Inc.',         type: 'Stock', exchange: 'NYSE',   last_price: 41.23,   expense_ratio: 0,      div_yield: 6.5  },
  { ticker: 'CMCSA',name: 'Comcast Corporation',                 type: 'Stock', exchange: 'NASDAQ', last_price: 40.88,   expense_ratio: 0,      div_yield: 3.5  },
];

// ─── Benchmark indexes ────────────────────────────────────────────────────────
// Offers both CBOE index tickers and ETF equivalents.
// ETFs (SPY, QQQ, etc.) work better with live data providers like Finnhub.
export const BENCHMARKS = [
  'SPY', 'QQQ', 'IWM', 'DIA',           // ETF equivalents (tradeable, reliable live data)
  'SPX', 'NDX', 'RUT', 'DJI',           // CBOE index tickers
  'EFA', 'AGG',                           // International & bonds
];

export const BENCHMARK_META = {
  'SPY':   { label: 'S&P 500 (SPY)',         description: 'SPDR S&P 500 ETF — large-cap US equities',        color: '#3b82f6' },
  'QQQ':   { label: 'NASDAQ-100 (QQQ)',      description: 'Invesco QQQ Trust — top 100 NASDAQ companies',    color: '#8b5cf6' },
  'IWM':   { label: 'Russell 2000 (IWM)',    description: 'iShares Russell 2000 ETF — US small-cap equities',color: '#f59e0b' },
  'DIA':   { label: 'Dow Jones 30 (DIA)',    description: 'SPDR Dow Jones ETF — 30 blue-chip industrials',   color: '#10b981' },
  'SPX':   { label: 'S&P 500 (CBOE: SPX)',   description: 'CBOE S&P 500 index — 500 large-cap US equities',  color: '#3b82f6' },
  'NDX':   { label: 'NASDAQ-100 (CBOE: NDX)',description: 'CBOE NASDAQ-100 — top 100 non-financial companies',color: '#8b5cf6' },
  'RUT':   { label: 'Russell 2000 (CBOE: RUT)', description: 'CBOE Russell 2000 — US small-cap equities',    color: '#f59e0b' },
  'DJI':   { label: 'Dow Jones 30 (CBOE: DJI)', description: 'CBOE Dow Jones — 30 blue-chip industrials',    color: '#10b981' },
  'EFA':   { label: 'MSCI EAFE',             description: 'Developed international markets ex-US',           color: '#06b6d4' },
  'AGG':   { label: 'US Aggregate Bond',     description: 'Investment-grade US bond market',                 color: '#6b7280' },
};
